#ifndef SNL_STRINGTAB_H
#define SNL_STRINGTAB_H
#include "stringtab.h"


/* in this head file, I used a new data structure str_entry,
 * which is almost the same as entry, I need to find a way to 
 * concat string, because of Symbol definition, it is very 
 * hard to do concat string directly, so a new stringtab is 
 * a simple solution */
typedef struct str_entry {
	int len;			/* len is generated by strlen, so without '\0' */
//	int index;			/* probably is useless */
	char *str;			/* points to somewhere in str_array */
} *str_symbol;

/* a growing array datatype */
#ifndef STRLEN_MAX
#define STRLEN_MAX 1024
#endif

typedef struct string_array {
	char *array;
	int  num;	/* current size of array */
	/* array + num is the first free pointer */
	int  max;
}str_array;

enum {NINIT = 1, NGROW = 2};

int add_stringtab(str_array *, char *, int len, char **);

int concat_string(char *a, int lena, char *b, int lenb, str_array *arr);

str_symbol single_string(Symbol, str_array *);
str_symbol  append_string(str_symbol, Symbol, str_array *);

extern str_array id_arr;

extern str_array str_arr;

#endif /* SNL_STRINGTAB_H */
